replicaCount: 1

image:
  repository: 199837183662.dkr.ecr.us-east-2.amazonaws.com/scos/cota-tvier-adapter
  pullPolicy: Always

nameOverride: ""
fullnameOverride: ""

service:
  type: ClusterIP
  port: 80

resources:
  limits:
    cpu: 2
    memory: 4Gi
  requests:
    cpu: 2
    memory: 4Gi


nodeSelector: {}

tolerations: []

affinity: {}
